version: '3.7'

services:
    composer:
        image: composer:2.6.6
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["sh", "-c", "composer install --ignore-platform-reqs"]

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./infra/mysql/db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    migrate:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy
            composer:
                condition: service_completed_successfully
        entrypoint: ["sh", "-c", "php artisan migrate"]

    passport:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy
            migrate:
                condition: service_completed_successfully
        entrypoint: ["sh", "-c", "php artisan passport:install && php artisan passport:key"]

    php:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - composer
            - migrate
            - passport
        command: ["php-fpm"]

    nginx:
        image: nginx:1.25.3
        volumes:
            - ./:/var/www/html
            - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./infra/nginx_logs:/var/log/nginx
        ports:
            - ${APP_PORT}:80
        depends_on:
            - php